### ISSUE TITLE
User Session Epic

### ISSUE THREAD

**Issue by weisso5** [weisso5/TransactionAPIBenchmarker#4]
**Describe the solution you'd like**

- [ ] Users Table
- [ ] FK to Transactions
- [ ] Simulated Login Page (No Password)
- [ ] User Session
- [ ] Require User Token on Request
- [ ] Basic User Request Tracking
- [ ] Simulated Dashboard
- [ ] Populate with Fake Data
